### ISSUE TITLE
Fix found, instructions inside - No method or instructions exist to change default keyboard controls (Win)

### ISSUE THREAD

**Issue by ArcadaLabs-Jason** [yancharkin/SpelunkyClassicHD#16]
Hi, I'm trying to figure out how to change the default controls. Are they unchangeable? There don't appear to be any instructions anywhere. I tried dropping in a keys.cfg from the official Spelunky Classic, didn't work.

Thanks!

**Comment by ArcadaLabs-Jason** [comment]
For anyone else stumbling upon this, I figured it out by reading the source code a bit.

The game loads a file "keys.json" for keyboard controls, and "gamepad.json" from the game directory if they exist. The keys for the json can be copied respectively from:

- https://github.com/yancharkin/SpelunkyClassicHD/blob/master/scripts/joySave.gml
- https://github.com/yancharkin/SpelunkyClassicHD/blob/master/scripts/keysSave.gml

Looks like the gamepad.json just loads by button number, keyboard keys load by ascii number. Here's a reference for ascii codes for the keyboard keys:

http://www.davetech.co.uk/gamemakerkeyboardasciicodes

And here's my keys.json file with a WASD mapping:

`
{
	"keyUpVal": 87,
	"keyDownVal": 83,
	"keyLeftVal": 65,
	"keyRightVal": 68,
	"keyJumpVal": 76,
	"keyAttackVal": 75,
	"keyItemVal": 77,
	"keyRunVal": 16,
	"keyBombVal": 79,
	"keyRopeVal": 73,
	"keyFlareVal": 70,
	"keyPayVal": 80
}
`

Note that the J key is off limits - it's apparently hardcoded (I think) as some kind of super jump. I prefer J and K for attack and jump, but no go. I also attempted to add comments with the keys used to the json file, but it causes the game to crash on launch.

Would be nice to be able to set the super jump key via this file as well.

**Comment by yancharkin** [comment]
Press ESC =>
![menu](https://user-images.githubusercontent.com/12972830/145856259-dbfd9f52-cb55-4bcc-922d-1b6ad757f02e.png)

**Comment by ArcadaLabs-Jason** [comment]
*facepalm*

Thanks haha

**Comment by yancharkin** [comment]
:)

**Comment by yancharkin** [comment]
Also, 'J' is indeed hardcoded to a higher jump. I don't remember details now, but it was done because 'jump' wasn't working when using touch buttons. It is possible (and easy) to assign a different key or disable it. Sadly it requires recompiling the game. Setting up an environment for this task will take too much time. I'm not going to do that. If you want to do it yourself, you have to remove/replace first if block [here](https://github.com/yancharkin/SpelunkyClassicHD/blob/c5b7a36f14830d57b44e6314c3fac7e2ada2ba59/objects/oGame.object.gmx#L630). Uncomment [this line](https://github.com/yancharkin/SpelunkyClassicHD/blob/c5b7a36f14830d57b44e6314c3fac7e2ada2ba59/scripts/enableTouchInput.gml#L27) and comment line after it.
