### ISSUE TITLE
Linux 64 bit build

### ISSUE THREAD

**Issue by Alexander-Wilms** [yancharkin/SpelunkyClassicHD#3]
Could you please upload a 64 bit build is possible? Currently one has to install quite a few 32 bit libraries.

**Comment by yancharkin** [comment]
I don't think engine capable of creating 64-bit builds (I almost sure it can't). Also I don't have access to Windows machine, so I can't  help you, sorry.

**Comment by rien333** [comment]
> I don't think engine capable of creating 64-bit builds (I almost sure it can't).

Do you have a source for this? It's pretty important to many, given that since 2018, a lot of distros have largely stopped supporting 32bit. I highly doubt creating 64bit versions is impossible after more than a decade of it being mainstream. 

I think I might have found some evidence to the contrary,  [in this thread](https://forum.yoyogames.com/index.php?threads/yyc-on-linux-doesnt-work.67922/). A lot of people here absolutely don't know what they're doing, so it's pretty difficult to see what their exact problems are. Nevertheless, on apr 7, 2020, one of the GameMaker developers wrote

> [linux] has to be 64bit for YYC."

So I think ever since you closed this issue, things might have changed a lot. You should at least reopen it, given that 64bit support is something that will probably eventually come around.

**Comment by yancharkin** [comment]
This version made with GameMaker 1.4 and it can't create 64-bit executables. The thread, you're references to, is about GameMaker 2. It looks like it capable of creating 64-bit executables, but, first, you have to buy it and, second, you have to port the game to a new engine. At the moment I'm not going to do any of this and very unlikely that I'll change my mind in the future. 
Of course, I'm aware that running 32-bit executables can be problematic on modern Linux distros, that's why I created this version: https://github.com/yancharkin/SpelunkyClassicHDhtml5/releases
That's the best I can do.

**Comment by rien333** [comment]
Thanks for your response, I understand the situation much better now (in addition to the work required to port this to 64bit). I actually knew barely anything about Gamemaker, so I'm sorry for coming in at this uninformed. 

I'll have a look at the html5 version.

**Comment by yancharkin** [comment]
It's OK. Actually, your post made me realize, that it's not obvious that builds for Linux (amd64, arm64, armv7l) or macOS exist (even if it's HTML5 version). I added this info to the README and release page.

**Comment by rien333** [comment]
Yeah, the html5 version seemed to work fine. Thanks for your work!
